image: commit451/android-config:latest

before_script:
  # Make sure that there won't be any interactive prompts that await user interaction
  - unset DISPLAY
  - export TERM=dumb
  - export _JAVA_OPTIONS="-Djava.awt.headless=true"
  # Increase the heap size to 3 GB for faster builds
  - export JAVA_OPTS="-Xmx3G"
  # Make the gradle wrapper executable
  - chmod +x gradlew

build:
  script:
    - ./gradlew testFdroidDebug --stacktrace
