image: commit451/android-config:latest

before_script:
  # Make sure that we are not trying to print anything to the console
  - unset DISPLAY
  - export TERM=dumb
  - export _JAVA_OPTIONS="-Djava.awt.headless=true"
  # Increase the heap size to 3 GB for faster builds
  - export JAVA_OPTS="-Xmx3G"
  # Make Gradle executable
  - chmod +x gradlew

build:
  script:
    # Run the build script, excluding the fabric tasks since they will fail with no proper API key
    - ./gradlew build --stacktrace
