image: webratio/android-sdk:r24.4.1

before_script:
  # Make sure that we are not trying to print anything to the console
  - unset DISPLAY
  - export TERM=dumb
  - export _JAVA_OPTIONS="-Djava.awt.headless=true"
  # Make Gradle executable
  - chmod +x gradlew

build:
  script:
    # Run the build script, excluding the fabric tasks since they will fail with no proper API key
    - ./gradlew build -x fabricGenerateResourcesRelease --stacktrace
