image: commit451/android-sdk-installer:latest

before_script:
  - android-sdk-installer

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleFdroidDebug

test:
  stage: test
  script:
    - ./gradlew testFdroidDebug
